name: payment_native
description: Secure payment processing with native SDKs
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.superapp.payment_native
        pluginClass: PaymentNativePlugin
      ios:
        pluginClass: PaymentNativePlugin
